### ISSUE TITLE
Arms are hard to animate

### ISSUE THREAD

**Issue by jaxonRuiz** [Game-Development-Club/7-Days-To-Nuke#8]
When animating arms, I have to redraw every frame like I did for the legs, instead of a simple movement and shading change like for the head. I need help?

**Comment by Stevemmm** [comment]
I think that you should try to ask some of the artists about some shading stuff and realistic movement for characters.

**Comment by jaxonRuiz** [comment]
No, I am perfectly able to animate the arms on my own, I just might need a little longer to finish the full character.

**Comment by Stevemmm** [comment]
Yea its alright. We have time for now.

**Comment by Stevemmm** [comment]
Alright I am now making this test issue a closed issue.
